export interface MusicTrack {
  id: string;
  title: string;
  artist: string;
  category: 'Apertura' | 'Bienvenida' | 'Meditación' | 'Respiración' | 'Conexión' | 'Reflexión' | 'Liberación' | 'Movimiento' | 'Gratitud' | 'Cierre';
  type: string;
  style?: string;
  isInstrumental: boolean;
  instrumental?: boolean;
  energyLevel: 'Bajo' | 'Medio' | 'Alto';
  duration: string;
  recommendedMoment: string;
  whyItFits: string;
  neuroacousticFoundation?: string;
  audioUrl?: string;
  durationSeconds?: number | null;
}

export const OFFICIAL_PLAYLISTS: MusicTrack[] = [
  {
    id: "music_001",
    title: "Forest Mist Whispers",
    artist: "Alejandro Magaña",
    category: "Bienvenida",
    type: "Ambient, naturaleza y atmósfera cálida",
    style: "Ambient, naturaleza y atmósfera cálida",
    isInstrumental: true,
    instrumental: true,
    energyLevel: "Bajo",
    duration: "Cargando duración...",
    recommendedMoment: "Recepción de participantes, registro, llegada al espacio o acomodación inicial.",
    whyItFits: "Su textura ambiental suave y sus cambios graduales ayudan a reducir la sobrecarga auditiva del entorno y favorecen una transición tranquila hacia la experiencia. No presentar este efecto como tratamiento médico.",
    neuroacousticFoundation: "Su textura ambiental suave y sus cambios graduales ayudan a reducir la sobrecarga auditiva del entorno y favorecen una transición tranquila hacia la experiencia. No presentar este efecto como tratamiento médico.",
    audioUrl: "/Musica/1-forest-mist-whispers-Bienvenida-2.mp3",
    durationSeconds: null
  },
  {
    id: "music_002",
    title: "Serene View",
    artist: "Arulo",
    category: "Bienvenida",
    type: "Ambient suave y contemplativo",
    style: "Ambient suave y contemplativo",
    isInstrumental: true,
    instrumental: true,
    energyLevel: "Bajo",
    duration: "Cargando duración...",
    recommendedMoment: "Entrada de los participantes, bienvenida informal o preparación del espacio.",
    whyItFits: "La dinámica estable y la ausencia de letra reducen la competencia con la conversación, ayudando a crear una atmósfera serena y receptiva.",
    neuroacousticFoundation: "La dinámica estable y la ausencia de letra reducen la competencia con la conversación, ayudando a crear una atmósfera serena y receptiva.",
    audioUrl: "/Musica/1-Serene-view-Bienvenida-1.mp3",
    durationSeconds: null
  },
  {
    id: "music_003",
    title: "Indian Meditations",
    artist: "Ahjay Stelino",
    category: "Apertura",
    type: "Meditación oriental, flauta y percusión suave",
    style: "Meditación oriental, flauta y percusión suave",
    isInstrumental: true,
    instrumental: true,
    energyLevel: "Medio",
    duration: "Cargando duración...",
    recommendedMoment: "Apertura ceremonial, establecimiento de intenciones o formación del círculo inicial.",
    whyItFits: "La combinación de elementos melódicos sostenidos y percusión moderada favorece la atención compartida y marca el comienzo formal de la experiencia.",
    neuroacousticFoundation: "La combinación de elementos melódicos sostenidos y percusión moderada favorece la atención compartida y marca el comienzo formal de la experiencia.",
    audioUrl: "/Musica/2-indian-meditations-Apertura-2.mp3",
    durationSeconds: null
  },
  {
    id: "music_004",
    title: "Spiritual Meditation",
    artist: "The_Mountain",
    category: "Apertura",
    type: "Ambient espiritual y meditación ceremonial",
    style: "Ambient espiritual y meditación ceremonial",
    isInstrumental: true,
    instrumental: true,
    energyLevel: "Bajo",
    duration: "Cargando duración...",
    recommendedMoment: "Lectura de intención, apertura espiritual, encendido de vela o ritual inicial.",
    whyItFits: "Su evolución lenta deja espacio para la voz del facilitador y ayuda a establecer un ritmo más pausado y contemplativo.",
    neuroacousticFoundation: "Su evolución lenta deja espacio para la voz del facilitador y ayuda a establecer un ritmo más pausado y contemplativo.",
    audioUrl: "/Musica/2-the_mountain-spiritual-meditation-Apertura-1.mp3",
    durationSeconds: null
  },
  {
    id: "music_005",
    title: "Deep Meditation",
    artist: "Grand_Project",
    category: "Meditación",
    type: "Ambient profundo y meditación prolongada",
    style: "Ambient profundo y meditación prolongada",
    isInstrumental: true,
    instrumental: true,
    energyLevel: "Bajo",
    duration: "Cargando duración...",
    recommendedMoment: "Meditaciones largas, visualización, escaneo corporal o descanso consciente.",
    whyItFits: "La continuidad sonora y la baja variación dinámica reducen interrupciones atencionales y acompañan ejercicios prolongados de concentración.",
    neuroacousticFoundation: "La continuidad sonora y la baja variación dinámica reducen interrupciones atencionales y acompañan ejercicios prolongados de concentración.",
    audioUrl: "/Musica/3-deep-meditation-meditacion-2.mp3",
    durationSeconds: null
  },
  {
    id: "music_006",
    title: "Meditation Healing",
    artist: "leberch",
    category: "Meditación",
    type: "Ambient relajante y paisajes sonoros suaves",
    style: "Ambient relajante y paisajes sonoros suaves",
    isInstrumental: true,
    instrumental: true,
    energyLevel: "Bajo",
    duration: "Cargando duración...",
    recommendedMoment: "Relajación guiada, meditación corporal, visualización o pausa restaurativa.",
    whyItFits: "La instrumentación suave y sin letra disminuye la carga verbal y permite que las indicaciones del facilitador permanezcan en primer plano.",
    neuroacousticFoundation: "La instrumentación suave y sin letra disminuye la carga verbal y permite que las indicaciones del facilitador permanezcan en primer plano.",
    audioUrl: "/Musica/3-meditation-healing-Meditacion-2.mp3",
    durationSeconds: null
  },
  {
    id: "music_007",
    title: "Handpan Meditation 432Hz",
    artist: "JuliusH",
    category: "Respiración",
    type: "Handpan, ambient y percusión melódica",
    style: "Handpan, ambient y percusión melódica",
    isInstrumental: true,
    instrumental: true,
    energyLevel: "Bajo",
    duration: "Cargando duración...",
    recommendedMoment: "Respiración consciente, regulación del ritmo, coherencia respiratoria o preparación meditativa.",
    whyItFits: "El patrón repetitivo del handpan puede funcionar como referencia temporal para acompañar inhalaciones y exhalaciones lentas. No atribuir efectos clínicos especiales a la frecuencia 432 Hz.",
    neuroacousticFoundation: "El patrón repetitivo del handpan puede funcionar como referencia temporal para acompañar inhalaciones y exhalaciones lentas. No atribuir efectos clínicos especiales a la frecuencia 432 Hz.",
    audioUrl: "/Musica/4-handpan-meditation-Respiracion-1.mp3",
    durationSeconds: null
  },
  {
    id: "music_008",
    title: "Relaxing Handpan Piano Music",
    artist: "kalsstockmedia",
    category: "Respiración",
    type: "Handpan, piano y ambient relajante",
    style: "Handpan, piano y ambient relajante",
    isInstrumental: true,
    instrumental: true,
    energyLevel: "Bajo",
    duration: "Cargando duración...",
    recommendedMoment: "Respiración diafragmática, relajación corporal o transición hacia una meditación.",
    whyItFits: "La repetición suave y la instrumentación espaciosa permiten sincronizar la respiración sin imponer un ritmo demasiado intenso.",
    neuroacousticFoundation: "La repetición suave y la instrumentación espaciosa permiten sincronizar la respiración sin imponer un ritmo demasiado intenso.",
    audioUrl: "/Musica/4-relaxing-handpan-piano-Respiracion-2.mp3",
    durationSeconds: null
  },
  {
    id: "music_009",
    title: "A Love Theme",
    artist: "Eugenio Mininni",
    category: "Conexión",
    type: "Piano emocional y ambient cálido",
    style: "Piano emocional y ambient cálido",
    isInstrumental: true,
    instrumental: true,
    energyLevel: "Bajo",
    duration: "Cargando duración...",
    recommendedMoment: "Ejercicios en parejas, escucha consciente, reconocimiento mutuo o fortalecimiento de vínculos.",
    whyItFits: "La melodía cálida puede ayudar a sostener un ambiente emocionalmente seguro sin distraer de la interacción interpersonal.",
    neuroacousticFoundation: "La melodía cálida puede ayudar a sostener un ambiente emocionalmente seguro sin distraer de la interacción interpersonal.",
    audioUrl: "/Musica/5-love-theme-conexion-1.mp3",
    durationSeconds: null
  },
  {
    id: "music_010",
    title: "You and Me",
    artist: "Michael Ramir C.",
    category: "Conexión",
    type: "Acústico cálido y emocional ligero",
    style: "Acústico cálido y emocional ligero",
    isInstrumental: true,
    instrumental: true,
    energyLevel: "Medio",
    duration: "Cargando duración...",
    recommendedMoment: "Actividades de presentación, conversaciones en parejas o integración grupal ligera.",
    whyItFits: "Su carácter amable y estable acompaña la interacción social y puede reducir la sensación de silencio incómodo.",
    neuroacousticFoundation: "Su carácter amable y estable acompaña la interacción social y puede reducir la sensación de silencio incómodo.",
    audioUrl: "/Musica/5-you-and-me-conexion-2.mp3",
    durationSeconds: null
  },
  {
    id: "music_011",
    title: "Possible Dreams",
    artist: "Eugenio Mininni",
    category: "Reflexión",
    type: "Piano contemplativo y cinematográfico suave",
    style: "Piano contemplativo y cinematográfico suave",
    isInstrumental: true,
    instrumental: true,
    energyLevel: "Bajo",
    duration: "Cargando duración...",
    recommendedMoment: "Escritura personal, journaling, visualización de propósito o preguntas de introspección.",
    whyItFits: "La música lenta y sin letra deja espacio para el pensamiento interno y evita interferir con procesos de escritura o reflexión.",
    neuroacousticFoundation: "La música lenta y sin letra deja espacio para el pensamiento interno y evita interferir con procesos de escritura o reflexión.",
    audioUrl: "/Musica/6-possible-dreams-Reflexion-1.mp3",
    durationSeconds: null
  },
  {
    id: "music_012",
    title: "Staring at the Night Sky",
    artist: "Alejandro Magaña",
    category: "Reflexión",
    type: "Ambient nocturno y contemplativo",
    style: "Ambient nocturno y contemplativo",
    isInstrumental: true,
    instrumental: true,
    energyLevel: "Bajo",
    duration: "Cargando duración...",
    recommendedMoment: "Silencio guiado, contemplación, cierre del día o reflexión individual.",
    whyItFits: "Las texturas amplias y pausadas ayudan a mantener una atmósfera de quietud y baja estimulación.",
    neuroacousticFoundation: "Las texturas amplias y pausadas ayudan a mantener una atmósfera de quietud y baja estimulación.",
    audioUrl: "/Musica/6-staring-at-the-night-sky-reflexion-2.mp3",
    durationSeconds: null
  },
  {
    id: "music_013",
    title: "Drawing the Sky",
    artist: "Eugenio Mininni",
    category: "Liberación",
    type: "Cinemático emocional y progresivo",
    style: "Cinemático emocional y progresivo",
    isInstrumental: true,
    instrumental: true,
    energyLevel: "Medio",
    duration: "Cargando duración...",
    recommendedMoment: "Movimiento emocional, expresión corporal, escritura liberadora o transición después de una actividad intensa.",
    whyItFits: "Su desarrollo progresivo permite acompañar un aumento gradual de la expresión y posteriormente facilitar una disminución controlada de la intensidad.",
    neuroacousticFoundation: "Su desarrollo progresivo permite acompañar un aumento gradual de la expresión y posteriormente facilitar una disminución controlada de la intensidad.",
    audioUrl: "/Musica/7-drawing-the-sky-Liberacion-1.mp3",
    durationSeconds: null
  },
  {
    id: "music_014",
    title: "Silent Descent",
    artist: "Eugenio Mininni",
    category: "Liberación",
    type: "Ambient emocional y melancólico",
    style: "Ambient emocional y melancólico",
    isInstrumental: true,
    instrumental: true,
    energyLevel: "Bajo",
    duration: "Cargando duración...",
    recommendedMoment: "Procesamiento emocional, liberación contenida, reflexión posterior o acompañamiento silencioso.",
    whyItFits: "La instrumentación contenida sostiene la experiencia emocional sin imponer un ritmo acelerado ni competir con la voz del facilitador.",
    neuroacousticFoundation: "La instrumentación contenida sostiene la experiencia emocional sin imponer un ritmo acelerado ni competir con la voz del facilitador.",
    audioUrl: "/Musica/7-silent-descent-Liberacion-2.mp3",
    durationSeconds: null
  },
  {
    id: "music_015",
    title: "Dance with Me",
    artist: "Ahjay Stelino",
    category: "Movimiento",
    type: "Rítmico, alegre y dinámico",
    style: "Rítmico, alegre y dinámico",
    isInstrumental: true,
    instrumental: true,
    energyLevel: "Alto",
    duration: "Cargando duración...",
    recommendedMoment: "Movimiento libre, activación grupal, cambio de energía o celebración corporal.",
    whyItFits: "El pulso marcado facilita la coordinación del movimiento y ayuda a elevar la activación después de periodos prolongados de quietud.",
    neuroacousticFoundation: "El pulso marcado facilita la coordinación del movimiento y ayuda a elevar la activación después de periodos prolongados de quietud.",
    audioUrl: "/Musica/8-dance-with-me-Movimiento-1.mp3",
    durationSeconds: null
  },
  {
    id: "music_016",
    title: "Feel Alive",
    artist: "Michael Ramir C.",
    category: "Movimiento",
    type: "Rítmico, positivo y motivador",
    style: "Rítmico, positivo y motivador",
    isInstrumental: true,
    instrumental: true,
    energyLevel: "Alto",
    duration: "Cargando duración...",
    recommendedMoment: "Activación física, dinámica grupal, recuperación de energía o transición después de una pausa.",
    whyItFits: "El ritmo constante y la energía ascendente facilitan el movimiento espontáneo y aumentan la sensación de dinamismo grupal.",
    neuroacousticFoundation: "El ritmo constante y la energía ascendente facilitan el movimiento espontáneo y aumentan la sensación de dinamismo grupal.",
    audioUrl: "/Musica/8-feel-alive-movimiento-2.mp3",
    durationSeconds: null
  },
  {
    id: "music_017",
    title: "Special Days",
    artist: "Ahjay Stelino",
    category: "Gratitud",
    type: "Acústico, luminoso y emocional",
    style: "Acústico, luminoso y emocional",
    isInstrumental: true,
    instrumental: true,
    energyLevel: "Medio",
    duration: "Cargando duración...",
    recommendedMoment: "Círculo de agradecimiento, reconocimiento de aprendizajes o celebración serena.",
    whyItFits: "Su tono luminoso acompaña emociones positivas y permite cerrar una actividad desde la apreciación sin elevar demasiado la intensidad.",
    neuroacousticFoundation: "Su tono luminoso acompaña emociones positivas y permite cerrar una actividad desde la apreciación sin elevar demasiado la intensidad.",
    audioUrl: "/Musica/9-special-days-gratitud-1.mp3",
    durationSeconds: null
  },
  {
    id: "music_018",
    title: "Tears of Joy",
    artist: "Michael Ramir C.",
    category: "Gratitud",
    type: "Emocional, cálido y esperanzador",
    style: "Emocional, cálido y esperanzador",
    isInstrumental: true,
    instrumental: true,
    energyLevel: "Medio",
    duration: "Cargando duración...",
    recommendedMoment: "Agradecimiento grupal, reconocimiento personal, entrega de mensajes o ceremonia de apreciación.",
    whyItFits: "La progresión emocional favorece un ambiente de reconocimiento y conexión, manteniendo suficiente espacio para la expresión verbal.",
    neuroacousticFoundation: "La progresión emocional favorece un ambiente de reconocimiento y conexión, manteniendo suficiente espacio para la experiencia verbal.",
    audioUrl: "/Musica/9-tears-of-joy-gratitud-2.mp3",
    durationSeconds: null
  },
  {
    id: "music_019",
    title: "Forever in My Heart",
    artist: "Michael Ramir C.",
    category: "Cierre",
    type: "Piano emocional y despedida cálida",
    style: "Piano emocional y despedida cálida",
    isInstrumental: true,
    instrumental: true,
    energyLevel: "Bajo",
    duration: "Cargando duración...",
    recommendedMoment: "Ceremonia final, despedida, integración del aprendizaje o cierre emocional.",
    whyItFits: "La melodía cálida y de resolución ayuda a marcar el final de la experiencia y acompaña una transición gradual hacia la despedida.",
    neuroacousticFoundation: "La melodía cálida y de resolución ayuda a marcar el final de la experiencia y acompaña una transición gradual hacia la despedida.",
    audioUrl: "/Musica/10-forever-in-my-heart-cierre-1.mp3",
    durationSeconds: null
  },
  {
    id: "music_020",
    title: "Lullaby Night",
    artist: "Diego Nava",
    category: "Cierre",
    type: "Ambient nocturno, piano suave y relajante",
    style: "Ambient nocturno, piano suave y relajante",
    isInstrumental: true,
    instrumental: true,
    energyLevel: "Bajo",
    duration: "Cargando duración...",
    recommendedMoment: "Cierre tranquilo, descanso nocturno, integración silenciosa o despedida serena.",
    whyItFits: "La baja intensidad y el ritmo pausado ayudan a disminuir la activación después de una jornada emocional o físicamente intensa.",
    neuroacousticFoundation: "La baja intensidad y el ritmo pausado ayudan a disminuir la activación después de una jornada emocional o físicamente intensa.",
    audioUrl: "/Musica/10-lullaby-night-cierre-2.mp3",
    durationSeconds: null
  }
];
